name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: dotnet setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: dotnet restore
      run: dotnet restore
    - name: dotnet build
      run: dotnet build --no-restore
    - name: dotnet test
      run: dotnet test --no-build --verbosity normal
